logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    com.mostafa.airbnbbackend: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: airbnb-backend
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER}

server:
  port: 8081

auth0:
  audience: ${AUTH0_AUDIENCE}
  client-id: ${AUTH0_CLIENT_ID}
  client-secret: ${AUTH0_CLIENT_SECRET}
  domain: ${AUTH0_ISSUER}
  role-landlord-id: ${AUTH0_ROLE_LANDLORD_ID}
