logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    com.mostafa.airbnbbackend: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: airbnb-backend
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    enabled: true
  #    drop-first: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8081


okta:
  oauth2:
    issuer: https://airbnb-backend.us.auth0.com/
    client-id: FNlkLniuKXbkXi7dKZP2SKOHUDBuR0B2
    client-secret: RlUl5QEkLHof-3-aBIvyv3su10LIVv2Ifg0EwslayIPWalsr_gYmftbDBctA-T6w

application:
  auth0:
    role-landlord-id: rol_CRmDV1Jopx6SYhs0
