logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    com.mostafa.airbnbbackend: DEBUG
    liquibase: DEBUG

spring:
  application:
    name: airbnb-backend
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/airbnb_backend?createDatabaseIfNotExists=true
    driver-class-name: org.postgresql.Driver
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: airbnb_backend
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: airbnb_backend
    enabled: true
  #    drop-first: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8181

#okta:
#  oauth2:
#    issuer: https://airbnb-backend.us.auth0.com/
#    client-id: ${AUTH0_CLIENT_ID}
#    client-secret: ${AUTH0_CLIENT_SECRET}

application:
  auth0:
    role-landlord-id: rol_v1CpFU8josLg8YjC
