server:
  forward-headers-strategy: framework

logging:
  level:
    ROOT: info
    org.hibernate.SQL: INFO
    com.mostafa.airbnbbackend: INFO

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: airbnb_backend
  liquibase:
    contexts: prod
    default-schema: airbnb_backend

okta:
  oauth2:
    issuer: ${OKTA_OAUTH2_ISSUER}
    client-id: ${OKTA_OAUTH2_CLIENT_ID}
    client-secret: ${OKTA_OAUTH2_CLIENT_SECRET}

application:
  auth0:
    role-landlord-id: ${AUTH0_ROLE_LANDLORD_ID}
